spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://122.205.5.3:19201/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      url: jdbc:mysql://localhost:19201/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: HUSTeic2021
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置jpa
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.li.entity

logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: spring.log
